//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEOAutomation.Base.Models.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdwordConfig
    {
        public int ID { get; set; }
        public string URL { get; set; }
        public string KeyWord { get; set; }
        public string LinkQuantityClick { get; set; }
        public string IntervalClick { get; set; }
        public Nullable<bool> IsBackLink { get; set; }
        public string TextLink { get; set; }
        public Nullable<bool> IsAdsen { get; set; }
        public Nullable<int> PageLimit { get; set; }
        public string TextBackLink { get; set; }
    }
}
